version: '3'
networks:
    cluster:
        external:
            name: cluster
services:
    mongo:
        container_name: "mongo"
        networks: 
            cluster:
                ipv4_address: 10.100.100.2
                aliases:
                    - mongo
        image: mongo       
    mariadb:
        tty: true
        container_name: "mariadb"
        networks:
          cluster:
            ipv4_address: 10.100.100.3
            aliases:
              - mariadb
        image: mariadb
        ports:
          - "3306:3306"
        volumes:
            - /root:/DATA
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: LAB
    python:
        container_name: "python"
        networks:
            cluster:
                ipv4_address: 10.100.100.4
                aliases:
                    - python
        image: deb_py
        volumes:
            - /root:/PY3
        command: tail -f /etc/passwd > /dev/null